// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReactApp.Server.Data;

#nullable disable

namespace ReactApp.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250316185837_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("ReactApp.Server.Data.Client", b =>
                {
                    b.Property<int>("Id_Client")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id_Client");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Actif");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Adresse");

                    b.Property<DateTime>("Date_Inscription")
                        .HasColumnType("TEXT")
                        .HasColumnName("Date_Inscription");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Nom");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Telephone");

                    b.HasKey("Id_Client");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ReactApp.Server.Data.Utilisateur", b =>
                {
                    b.Property<int>("id_utilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("est_administrateur")
                        .HasColumnType("INTEGER")
                        .HasColumnName("est_administrateur");

                    b.Property<string>("mot_de_passe")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mot_de_passe");

                    b.Property<string>("nom_utilisateur")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nom_utilisateur");

                    b.HasKey("id_utilisateur");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("ReactApp.Server.Data.UtilisateursClients", b =>
                {
                    b.Property<int>("id_utilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_utilisateur");

                    b.Property<int>("id_client")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_client");

                    b.HasKey("id_utilisateur");

                    b.ToTable("UtilisateursClients");
                });

            modelBuilder.Entity("ReactApp.Server.Data.VueUtilisateurActivites", b =>
                {
                    b.Property<int>("Id_Utilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("Adresse_Client")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("adresse_client");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("EstAdministrateur")
                        .HasColumnType("INTEGER")
                        .HasColumnName("est_administrateur");

                    b.Property<string>("Mot_de_passe")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mot_de_passe");

                    b.Property<string>("Nom_Client")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nom_client");

                    b.Property<string>("Nom_Utilisateur")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nom_utilisateur");

                    b.Property<int>("Nombre_Decodeurs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("nombre_decodeurs");

                    b.Property<int>("Nombre_Operations")
                        .HasColumnType("INTEGER")
                        .HasColumnName("nombre_operations");

                    b.HasKey("Id_Utilisateur");

                    b.ToTable("Vue_Utilisateur_Activites");
                });
#pragma warning restore 612, 618
        }
    }
}
