// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReactApp.Server.Data;

#nullable disable

namespace ReactApp.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250302214918_authentification")]
    partial class authentification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("ReactApp.Server.Data.Client", b =>
                {
                    b.Property<int>("id_client")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_client");

                    b.Property<bool>("actif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("date_inscription")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id_client");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ReactApp.Server.Data.Utilisateur", b =>
                {
                    b.Property<int>("id_utilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_utilisateur");

                    b.Property<DateTime>("date_creation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("derniere_connexion")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("est_administrateur")
                        .HasColumnType("INTEGER");

                    b.Property<string>("mot_de_passe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nom_utilisateur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id_utilisateur");

                    b.ToTable("Utilisateurs");
                });
#pragma warning restore 612, 618
        }
    }
}
